import {
    FiCpu,
    FiMapPin,
    FiUsers,
    FiTag,
} from "react-icons/fi";

import type { AIAnalysis } from "../../hooks/useAIAnalysis";

interface Props {
    analysis: AIAnalysis;
}

function Section({
    title,
    items,
    icon,
}: {
    title: string;
    items: string[];
    icon: React.ReactNode;
}) {
    return (
        <div>

            <div className="mb-3 flex items-center gap-2 text-white">

                {icon}

                <h3 className="font-semibold">
                    {title}
                </h3>

            </div>

            {
                items.length === 0 ? (
                    <p className="text-sm text-slate-500">
                        None detected
                    </p>
                ) : (
                    <div className="flex flex-wrap gap-2">

                        {
                            items.map((item) => (
                                <span
                                    key={item}
                                    className="
                                        rounded-full
                                        bg-indigo-500/15
                                        px-3
                                        py-1
                                        text-sm
                                        text-indigo-300
                                    "
                                >
                                    {item}
                                </span>
                            ))
                        }

                    </div>
                )
            }

        </div>
    );
}

export default function AIAnalysisCard({
    analysis,
}: Props) {
    return (
        <section
            className="
                mt-8
                rounded-3xl
                border
                border-white/10
                bg-white/5
                p-8
                backdrop-blur-xl
            "
        >

            <div className="mb-8 flex items-center gap-3">

                <div
                    className="
                        flex
                        h-12
                        w-12
                        items-center
                        justify-center
                        rounded-2xl
                        bg-gradient-to-br
                        from-indigo-500
                        to-violet-600
                        text-white
                    "
                >
                    <FiCpu size={22} />
                </div>

                <div>

                    <h2 className="text-2xl font-bold text-white">
                        AI Analysis
                    </h2>

                    <p className="text-sm text-slate-400">
                        Generated by Gemini
                    </p>

                </div>

            </div>

            <div className="mb-8">

                <h3 className="mb-3 text-lg font-semibold text-white">
                    Genre
                </h3>

                <span
                    className="
                        rounded-full
                        bg-emerald-500/20
                        px-4
                        py-2
                        text-emerald-400
                    "
                >
                    {analysis.genre}
                </span>

            </div>

            <div className="space-y-8">

                <Section
                    title="Characters"
                    items={analysis.characters}
                    icon={<FiUsers />}
                />

                <Section
                    title="Locations"
                    items={analysis.locations}
                    icon={<FiMapPin />}
                />

                <Section
                    title="Themes"
                    items={analysis.themes}
                    icon={<FiTag />}
                />

            </div>

        </section>
    );
}